notifications:
  email: false
  slack: colmena-cms:o0Inc1h1waa9OKMvL4GiTbDW
language: node_js
node_js:
  - '8'
install:
  - npm install -g @angular/cli lerna loopback-cli
  - npm install
script:
  - npm run build
cache:
  directories:
  - node_modules
deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/deploy-to-now.sh
    on:
      branch: develop

